# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BackTrackSolo' do
	pod 'libpd', '~> 0.7'
	pod 'MagicPie', '~> 1.0.1'
	pod 'XYPieChart', '~> 0.2'
end

target 'BackTrackSoloTests' do

end

