#Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BackTrackV2' do
	pod 'libpd', '~> 0.7'
	pod 'MIKMIDI', '~> 1.0'
end

target 'BackTrackV2Tests' do

end

